title: Project
preset: page
num: date
icon: 💾

status:
  draft:
    label: Draft
    text: The project is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The project is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The project is online and listed in the blog

fields:
  headline:
    type: text
    width: 3/4
    required: true
  year:
    type: number
    min: 2000
    default: 2018
    required: true
    width: 1/4
  tags:
    type: tags
  intro:
    label: Intro
    type: editor  
  overview:
    label: Overiew
    type: editor
  process:
    label: Process & Artifacts
    type: editor
  
sidebar:
  cover:
    type: files
    headline: Cover
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    min: 1
    max: 3
  gallery:
    type: files
    headline: Gallery
    template: image