title: Project
preset: page
num: date
icon: 💾

status:
  draft:
    label: Draft
    text: The project is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The project is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The project is online and listed in the blog

fields:
  headline:
    type: text
    width: 3/4
    required: true
  year:
    label: Project Year
    type: number
    min: 2000
    default: 2018
    required: true
    width: 1/4
  date:
    label: Posted Date
    type: date
    time: true
    default: now
    width: 1/4
  tags:
    type: tags
    width: 3/4
  intro:
    type: textarea
    size: small
  overview:
    type: textarea
    size: large
  process:
    type: textarea
    size: large
  author:
    type: users
    width: 1/2

sidebar:
  cover:
    type: files
    headline: Cover
    layout: cards
    info: '{{ file.dimensions }}'
    template: cover
    min: 1
    max: 3
  gallery:
    type: files
    headline: Gallery
    template: image

