title: Site

columns:
      - width: 1/2
        sections:
          articles: sections/articles
      - width: 1/2
        sections:
          notes: sections/notes
          pages:
            type: pages
            create: default
            template:
              - home
              - about
              - contact
