title: Site

tabs:

  # tab 1
  main:

    label: Content 
    icon: preview

    columns:
      - width: 1/2
          sections:
            projects: sections/projects

      - width: 1/2
          sections:
            notes: sections/notes

            articles: sections/articles

  # tab 2
  site:

      label: Site
      icon: globe

      columns:
        - width: 1/2
          sections:
            content:
              type: fields
              fields:
                author:
                  label: Author
                  type:  text
                description:
                  label: Description
                  type:  textarea
                  size:  small
                keywords:
                  label: Keywords
                  type:  tags
                copyright:
                  label: Copyright
                  type:  textarea

        - width: 1/2
          sections:
            pages:
              type: pages
              create: default
              image: false
              # -- pages shown by template
              template:
                - home
                - about
                - contact
                - default
              # -- available templates for new pages
              create:
                - default
