title: Site

tabs:

  # tab 1
  main:

    label: Content 
    icon: preview

    columns:
            - width: 1/2
                sections:
                  projects: sections/projects
 
                  pages:
                    type: pages
                    create: default
                    image: false
                    # -- pages shown by template
                    template:
                      - home
                      - about
                      - contact
                      - default
                    # -- available templates for new pages
                    create:
                      - default

            - width: 1/2
                sections:
                  notes: sections/notes

                  articles: sections/articles

  # tab 2
  siteinfo:

      label: Site Info
      icon: globe

      columns:
        - width: 1/2
          sections:
            content:
              type: fields
              fields:
                author:
                  label: Author
                  type:  text
                description:
                  label: Description
                  type:  textarea
                  size:  medium
        - width: 1/2
          sections:
            content2:
              type: fields
              fields:
                keywords:
                  label: Keywords
                  type:  tags
                copyright:
                  label: Copyright
                  type:  textarea
